services:
  # PHP Apache Web Server
  web:
    build:
      context: ../..
      dockerfile: Server/docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: ${PROJECT_NAME}_web
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ../..:/var/www/html
      - web_logs:/var/log/apache2
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PHP_ENV=${PHP_ENV:-development}
      - APP_URL=${APP_URL:-http://localhost}
    networks:
      - ${PROJECT_NAME}_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ${PROJECT_NAME}_mysql_data:/var/lib/mysql
      - ./mysql/${PROJECT_NAME}.sql:/docker-entrypoint-initdb.d/01-${PROJECT_NAME}.sql:ro
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/02-init.sql:ro
      - mysql_logs:/var/log/mysql
    networks:
      - ${PROJECT_NAME}_network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --innodb-buffer-pool-size=256M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-root123}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PROJECT_NAME}_phpmyadmin
    ports:
      - "${PMA_PORT:-8081}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      PMA_ABSOLUTE_URI: ${PMA_URL:-http://localhost:8081}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ${PROJECT_NAME}_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ${PROJECT_NAME}_mysql_data:
    driver: local
  mysql_logs:
    driver: local
  web_logs:
    driver: local

networks:
  ${PROJECT_NAME}_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
